### PR TITLE
Make GenericParser's buildTree iterative instead of recursive

### PR DESCRIPTION
**Pull request by gdesmar**
This is an improvement to transform the buildTree function from recursive to iterative, so that it does not hit the recursion limit in certain cases.

A few things I want to point out first:
1) This is not an "issue/bug" but a "potential improvement"
2) This may need better and thorough testing, as I may be missing some important context that I broke, mostly with the attr array initialization VS the _BOF attr skip
3) This problem has an alternative workaround, by increasing the recursion limit within python using:
```python
>>> import sys
>>> print(sys.getrecursionlimit())
>>> sys.setrecursionlimit(20000)
```
I am not a fan of the workaround, as the recursion limit needed is not known in advance (but could be increased gradually). It also reduce defences against other possible runaway code, even if done and undone as close as possible in a script.

Quick note: I also saw that the deriveEpsilon function is another recursive function, but it did not seem to cause issues, therefore I did not modify it.

## Example
A real life example is documented at the end of this Pull Request. A simpler [recursive.cpython-38.pyc.zip example](https://github.com/user-attachments/files/17234126/recursive.cpython-38.pyc.zip) to showcase the improvement can be generated with:
```bash
python -c "print('\n'.join(['10, '*20]*500))" > recursive.py
```

And then by modifying the recusive.py file to add the following: 
```python
l = [
###################
# CURRENT CONTENT #
###################
]
print(l)
```

Then, using a python 3.8 environment, by compiling with the following to generate the `__pycache__/recursive.cpython-38.pyc` file.
```python
>>> import py_compile
>>> py_compile.compile("recursive.py")
'__pycache__/recursive.cpython-38.pyc'
```

Starting a python 3.11 interpreter in that `__pycache__` folder, and testing the code using uncompyle6:
```python
>>> import os
>>> import uncompyle6
>>> uncompyle6.main.main(in_base=os.getcwd(), out_base=None, compiled_files=["recursive.cpython-38.pyc"], source_files=[], outfile=None)
# uncompyle6 version 3.9.1
# Python bytecode version base 3.8.0 (3413)
# Decompiled from: Python 3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
# Embedded file name: recursive.py
# Compiled at: 2024-09-27 19:40:25
# Size of source mod 2**32: 40517 bytes

maximum recursion depth exceeded in comparison


Last file: .../recursive.cpython-38.pyc   Traceback (most recent call last):
  File ".../spark_parser/spark.py", line 857, in buildTree
    attr[i] = self.buildTree(sym, why[0], tokens, why[1])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../spark_parser/spark.py", line 857, in buildTree
    attr[i] = self.buildTree(sym, why[0], tokens, why[1])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../spark_parser/spark.py", line 857, in buildTree
    attr[i] = self.buildTree(sym, why[0], tokens, why[1])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 995 more times]
  File ".../spark_parser/spark.py", line 850, in buildTree
    item, k = self.predecessor(key, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../spark_parser/spark.py", line 796, in predecessor
    for p, c in self.links[key]:
                ~~~~~~~~~~^^^^^
RecursionError: maximum recursion depth exceeded in comparison
```

The original recursive.py is obtained if my iterative buildTree function is used instead.

## Testing
I am not certain on how to test this library independently, but I tested my code using uncompyle6 at both the current [HEAD of master](https://github.com/rocky/python-uncompyle6/tree/710167b8069c5ce2bc82d921d64acb0cd3bcfab5) and [most recent release](https://github.com/rocky/python-uncompyle6/tree/3.9.2). I used python 3.8 and executed `make check`, which returned `Everything good, removing [...]` multiple time and at the end.

I would be happy to help if there are other tests that I have missed.

## Real life example
[77b42a34d23f8012b41286c9abfb369de52e6864c1263780613380660a168028](https://www.virustotal.com/gui/file/77b42a34d23f8012b41286c9abfb369de52e6864c1263780613380660a168028) (exe) 
-> 866181b644b164bb343a2c9adca97bba62883b6f070ed47750c25bbfe7296ce6 (pyc) 
--> d02b455cff9ea08dd0765bf99580805290b1fca4566b5de911c8e3ea70966c5e (py)

The final decompiled python is the following:
```python
from Crypto.IO import PEM
import ctypes
l = [148, 199, 218, 199, 197, 197, 197, 202, 202, 202, 202, 202, 165, 162,
 160, 174, 169, 199, 169, 136, 137, 130, 202, 202, 202, 202, 202,
 ... # Malicious content
 147, 158, 151, 130, 148, 201, 132, 184, 142, 137, 147, 207, 143,
 206, 203, 132, 147, 158, 151, 130, 148, 201, 132, 184, 142, 137,
 147, 207, 202, 214, 206, 206, 220]
de = [chr(i ^ 231) for i in l]
l = list(map(str, de))
l = "".join(de)
exec(l)
```

### CODE REVIEW

**Comment by rocky** [comment]
Many thanks for reporting and offering a potential fix (if not a total fix). I haven't looked at this code in a while but I will try to do so in the next couple of days. (If it is more than a week, ping me).

**Comment by rocky** [comment]
I just pulled it and tried it.  I love it! 

I rant it over its own unit tests as well as uncompyle6 and decompyle3 tests. 

Tree building is much faster and we can handle larger lists which greatly helps decompiling. 

As for the stuff that isn't implemented, generally speaking, there have been features in the code that aren't used. If they ever need to be used, we'll fix the code at that point in time. Or possibly I'll ditch this and use lark_parser which supposedly supports Eariley grammars now.

**Comment by gdesmar** [comment]
I was wondering how it would react speed-wise. Theory says that iterative is faster, but I had not tested it. I was curious if you did, and you still had the results around. 🙂

Thank you very much, I greatly appreciate your enthusiasm and am looking forward to make more Pull Requests if I find anything!

**Comment by rocky** [comment]
> I was wondering how it would react speed-wise. Theory says that iterative is faster, but I had not tested it. I was curious if you did, and you still had the results around. 🙂

I had not timed things before, so I just did.  Only a small difference. For your list of 10,000 10's, in 3.12.7:

iteration took 0:00:00.084571 seconds
recursion took 0:00:00.089305 seconds

> 
> Thank you very much, I greatly appreciate your enthusiasm and am looking forward to make more Pull Requests if I find anything!

Thanks. Open source is only as good as the work that people put into it.

**Comment by rocky** [comment]
@gdesmar FYI I have added you to the (newly created) [THANKS](https://github.com/rocky/python-spark/blob/master/THANKS) file. A release will occur soon, so please check the attribution and suggest changes as necessary. Thanks.

**Comment by gdesmar** [comment]
Awesome! Looks great. I will try to open my new PR on uncompyle6 today then!

**Comment by rocky** [comment]
Actually, for a day or so it may be a little more difficult.  The next spark-parser version is 1.9.0 and the last release of uncompyle6 is pinned to < 1.9.0.  However, if you build from the current github master source you will be okay. 

Over the next few days, I'll update uncompyle6 and decompile3 (and others) so that this gets picked up automatically from PYPI.

**Pull request merged**
